# Generated by Django 2.0.2 on 2019-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
